# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='background_image',
        ),
    ]
