# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='static/movies/images/no-img.png', upload_to='movies/static/movies/images'),
        ),
    ]
