# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20160727_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='movies/images/no-img.png', upload_to='static/movies/images'),
        ),
    ]
