# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20160727_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_link',
            field=models.CharField(default='http://www.imdb.com/search/title', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rotten_tomatoes_link',
            field=models.CharField(default='https://www.rottentomatoes.com/search/?search=', max_length=100),
        ),
    ]
