# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20160728_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
