# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 00:00
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_movie_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Ação', 'Ação'), ('Aventura', 'Aventura'), ('Animação', 'Animação'), ('Biográfico', 'Biográfico'), ('Clássicos', 'Classicos'), ('Comédia', 'Comédia'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Família', 'Família'), ('Fantasia', 'Fantasia'), ('Film_noir', 'Film-noir'), ('Histórico', 'Histórico'), ('Terror', 'Terror'), ('Musical', 'Musical'), ('Mistério', 'Mistério'), ('Romance', 'Romance'), ('Ficção Científica', 'Ficção Científica'), ('Esporte', 'Esporte'), ('Suspense', 'Suspense'), ('Guerra', 'Guerra'), ('Western', 'Western')], max_length=182),
        ),
    ]
