# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_auto_20160729_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='C:\\Users\\lfsan\\Documents\\web_dev\\cineice\\movies\\static\\movies\\images\\poster_not_available.jpg', upload_to='posters'),
        ),
    ]
