# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_auto_20160730_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='movies\\static\\movies\\images\\poster_not_available.jpg', upload_to='posters'),
        ),
    ]
