# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20160730_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_link',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rotten_tomatoes_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
