# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 08:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_auto_20160730_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rotten_tomatoes_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
