# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 12:57
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0028_auto_20160730_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('açao', 'Ação'), ('aventura', 'Aventura'), ('animacao', 'Animação'), ('biografico', 'Biográfico'), ('classicos', 'Classicos'), ('comedia', 'Comédia'), ('crime', 'Crime'), ('drama', 'Drama'), ('familia', 'Família'), ('fantasia', 'Fantasia'), ('filme_noir', 'Film-noir'), ('historico', 'Histórico'), ('terror', 'Terror'), ('musical', 'Musical'), ('misterio', 'Mistério'), ('romance', 'Romance'), ('ficçao_cientifica', 'Ficção Científica'), ('esporte', 'Esporte'), ('suspense', 'Suspense'), ('guerra', 'Guerra'), ('western', 'Western')], max_length=183),
        ),
    ]
